"""change running scripts 2

Revision ID: 477202b877ce
Revises: a1a34fc6992e
Create Date: 2022-05-16 20:52:18.607763

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '477202b877ce'
down_revision = 'a1a34fc6992e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('unique_running_script_user_status', 'running_scripts', ['user_id', 'status'], unique=True, postgresql_where=sa.text("status = 'active'"))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('unique_running_script_user_status', table_name='running_scripts', postgresql_where=sa.text("status = 'active'"))
    # ### end Alembic commands ###
