"""change running scripts

Revision ID: a1a34fc6992e
Revises: 7a21e813f3fa
Create Date: 2022-05-16 20:43:41.992724

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a1a34fc6992e'
down_revision = '7a21e813f3fa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('running_scripts', sa.Column('script_id', sa.BIGINT(), nullable=False))
    op.create_foreign_key(None, 'running_scripts', 'scripts', ['script_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'running_scripts', type_='foreignkey')
    op.drop_column('running_scripts', 'script_id')
    # ### end Alembic commands ###
