"""change actions

Revision ID: 7a21e813f3fa
Revises: 6171e0b5bc5f
Create Date: 2022-05-16 20:25:12.777461

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7a21e813f3fa'
down_revision = '6171e0b5bc5f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('actions', sa.Column('alias', sa.VARCHAR(), nullable=False))
    op.add_column('actions', sa.Column('start_action', sa.BOOLEAN(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('actions', 'start_action')
    op.drop_column('actions', 'alias')
    # ### end Alembic commands ###
